config/routes.rb
Rails.application.routes.draw do

  resources :experiments do
    resources :time_slots
  end
  root 'welcome#index'

  devise_for :users

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  belongs_to :researcher, foreign_key: "researcher_id", class_name: "User"
  has_many :time_slots
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  belongs_to :experiment
  belongs_to :researcher, foreign_key: "researcher_id", class_name: "User"
  has_one :subject, foreign_key: "subject_id", class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :experiments
  has_many :subject_time_slots, :foreign_key => 'subject_id', :class_name => 'Timeslot'
  has_many :researcher_time_slots, :foreign_key => 'researcher_id', :class_name => 'Timeslot'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :authenticate_role!, only: [:new, :create, :update, :edit, :destroy]
  before_action :can_modify!, only: [:update, :edit, :destroy]



  def authenticate_role!
    unless current_user.has_role?(:admin) or current_user.has_role?(:researcher)
      render status: :forbidden, text: "You do not have access to this page."
      return
    end
  end

  def can_modify!
    unless current_user.has_role?(:admin) or @experiment.researcher == cuurent_user
      render status: :forbidden, text: "You do not have access to this page."
      return
    end
  end

  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)
    @experiment.researcher = current_user
    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:title, :description, :is_active)
    end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_experiment
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = @experiment.time_slots
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = @experiment.time_slots.new(time_slot_params)
    # @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to experiment_time_slot_path(@experiment, @time_slot), notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    def set_experiment
      @experiment = Experiment.find(params[:experiment_id])
    end

    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:appointment_time, :researcher_id, :status, :subject_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing Experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Experiments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Researcher</th>
      <th>Is active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.title %></td>
        <td><%= experiment.description %></td>
        <td><%= experiment.researcher_id %></td>
        <td><%= experiment.is_active %></td>
        <td><%= link_to 'Show', experiment %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
        <td><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experiment', new_experiment_path %>

app/views/experiments/new.html.erb
<h1>New Experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @experiment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experiment.description %>
</p>

<p>
  <strong>Researcher:</strong>
  <%= @experiment.researcher_id %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @experiment.is_active %>
</p>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ganglion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if current_user %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% else %>
    <%= link_to('Login', new_user_session_path)  %>
<% end %>
<%= yield %>

</body>
</html>

app/views/time_slots/_form.html.erb
<%= form_for([@experiment, @experiment.time_slots.build]) do |f| %>
 <!--
  <%# if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <%# @time_slot.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>
-->
  <div class="field">
    <%= f.label :appointment_time %><br>
    <%= f.datetime_select :appointment_time %>
  </div>
  <div class="field">
    <%= f.label :researcher_id %><br>
    <%= f.number_field :researcher_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing Time Slot</h1>

<%#= render 'form' %>

<%= form_for([@experiment, @time_slot]) do |f| %>
    <div class="field">
      <%= f.label :appointment_time %><br>
      <%= f.datetime_select :appointment_time %>
    </div>
    <div class="field">
      <%= f.label :researcher_id %><br>
      <%= f.number_field :researcher_id %>
    </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.text_field :status %>
    </div>
    <div class="field">
      <%= f.label :subject_id %><br>
      <%= f.number_field :subject_id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Show', experiment_time_slot_path(@experiment, @time_slot) %> |
<%= link_to 'Back', experiment_time_slot_path %>

app/views/time_slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Time Slots</h1>

<table>
  <thead>
    <tr>
      <th>Belongs to</th>
      <th>Appointment time</th>
      <th>Duration</th>
      <th>Researcher</th>
      <th>Status</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiment.time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.experiment_id %></td>
        <td><%= time_slot.appointment_time %></td>
        <td><%= time_slot.duration %></td>
        <td><%= time_slot.researcher_id %></td>
        <td><%= time_slot.status %></td>
        <td><%= time_slot.subject_id %></td>
        <td><%= link_to 'Show', [time_slot.experiment, time_slot] %></td>
        <td><%= link_to 'Edit', edit_experiment_time_slot_path(@experiment, time_slot) %></td>
        <td><%= link_to 'Destroy', [time_slot.experiment, time_slot], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time slot', new_experiment_time_slot_path(@experiment) %>

app/views/time_slots/new.html.erb
<h1>New Time Slot</h1>

<%= render 'form' %>

<%= link_to 'Back', experiment_time_slots_path(@experiment) %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Experiment:</strong>
  <%= @time_slot.experiment_id %>
</p>

<p>
  <strong>Appointment time:</strong>
  <%= @time_slot.appointment_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @time_slot.duration %>
</p>


<p>
  <strong>Researcher:</strong>
  <%= @time_slot.researcher_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @time_slot.status %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @time_slot.subject_id %>
</p>

<%= link_to 'Edit', edit_experiment_time_slot_path(@experiment, @time_slot) %> |
<%= link_to 'Back', experiment_time_slots_path(@experiment) %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>